[Settings]
downloadfolder = ./av_scanners
maxworkers = 3

[Scanners]
drwebcureit = True
kasperskykvrt = True
emsisoftemergencykit = True
esetonlinescanner = True
adwcleaner = True

[ScannerUrls]
drwebcureit = https://free.drweb.ru/download+cureit/gr/
kasperskykvrt = http://devbuilds.kaspersky-labs.com/devbuilds/KVRT/latest/full/KVRT.exe
emsisoftemergencykit = https://dl.comss.org/download/EmsisoftEmergencyKit.exe
esetonlinescanner = https://download.eset.com/com/eset/tools/online_scanner/latest/esetonlinescanner.exe
adwcleaner = https://dl.comss.org/download/adwcleaner-beta.exe

[CustomUrls]
# добавьте свои ссылки (одна на строку)
# формат: имя = URL
custom1 = https://dl.surfright.nl/HitmanPro_x64.exe
custom2 = https://dl.comss.org/download/avz5.zip
custom3 = https://dl.comss.org/download/AVbr.zip
custom4 = https://download.sysinternals.com/files/Autoruns.zip
custom5 = https://download.sysinternals.com/files/ProcessExplorer.zip
custom6 = https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip
# custom7 = https://dragokas.com/tools/HiJackThis.zip
custom8 = https://dl.comss.org/download/SecurityCheck.zip
custom9 = https://github.com/doublecmd/doublecmd/releases/download/v1.2.8/doublecmd-1.2.8.x86_64-win64.zip
custom10 = https://dl.comss.org/download/mb5-setup-consumer-5.7.0.328-164.0.5736-1.0.114300.exe
