[Settings]
downloadfolder = ./av_scanners
maxworkers = 3
enablemalwarebytessearch = True

[Scanners]
malwarebytes = True
drwebcureit = True
kasperskykvrt = True
emsisoftemergencykit = True
esetonlinescanner = True
adwcleaner = True

[CustomUrls]
# добавьте свои ссылки (одна на строку) = 
# пример: = 
# custom1 = https://example.com/scanner1.exe
custom1 = https://dl.surfright.nl/HitmanPro_x64.exe
custom2 = https://dl.comss.org/download/avz5.zip
custom3 = https://dl.comss.org/download/AVbr.zip
custom4 = https://download.sysinternals.com/files/Autoruns.zip
custom5 = https://download.sysinternals.com/files/ProcessExplorer.zip
custom6 = https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip
custom7 = https://dragokas.com/tools/HiJackThis.zip
custom8 = https://dl.comss.org/download/SecurityCheck.zip
custom9 = https://dl.comss.org/download/tcmd1156x32_64.exe
